# all ranges that users can select as transmit ranges
transmitRanges:
  - 0
  - 10
  - 20
  - 50
  - 100
  - 200
  - 500
  - 1000
  - 10000
  - 100000
  - 7000000 # "Infinite"; the highest minecraft can go

# # all ranges that users can select as receive ranges
# if not configured, same as transmitRanges
# receiveRanges: []

# colors players can set their waypoint icon.
# the following list includes every allowed named color like this:
#   - color: black
#     displayName: Black
# but you can also set hex codes as allowed values like this:
#   - color: "#694269"
#     displayName: Custom Color
iconColors:
  - color: black
    displayName: Black
  - color: dark_blue
    displayName: Dark Blue
  - color: dark_green
    displayName: Dark Green
  - color: dark_aqua
    displayName: Dark Aqua
  - color: dark_red
    displayName: Dark Red
  - color: dark_purple
    displayName: Dark Purple
  - color: gold
    displayName: Gold
  - color: gray
    displayName: Gray
  - color: dark_gray
    displayName: Dark Gray
  - color: blue
    displayName: Blue
  - color: green
    displayName: Green
  - color: aqua
    displayName: Aqua
  - color: red
    displayName: Red
  - color: light_purple
    displayName: Light Purple
  - color: white
    displayName: White